### PR TITLE
Sarah bug fixes

### PR DESCRIPTION
**Pull request by see24**

### CODE REVIEW

**Comment by adricaswell** [comment]
Cannot generate report from restored file. Trying to generate report results in the following error:

```
Warning: Error in vec_rbind: `c()` method returned a vector of unexpected size 3 instead of 1.
ℹ In file c.c at line 412.
ℹ Install the winch package to get additional debugging info the next time you get this error.
ℹ This is an internal error that was detected in the vctrs package.
  Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex and the full backtrace.
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>
```

Downloads shows:
image

App doesn't crash, but report cannot be downloaded. Running spatial analysis and then trying to generate report does not resolve the issue.

**Comment by adricaswell** [comment]
Spatial data is not restored if spatial analysis was not run before saving progress. Instead, all spatial data input boxes show "NA".

**Comment by adricaswell** [comment]
There is a lag between the "Successfully restored from file" message and the file being restored. It takes time for the spatial analysis to be run, but before it is complete, the "Successfully restored from file" message. However, there is no data restored at this point. 

It would be great if more messaging could be added to prevent user confusions. Ex: "Restoring assessment from file..." when the file is opened, "Performing spatial analysis" to indicate spatial analysis is occurring, "Successfully restored from file" when spatial analysis is complete.

**Comment by see24** [comment]
> Spatial data is not restored if spatial analysis was not run before saving progress. Instead, all spatial data input boxes show "NA".

This one I am not going to worry about. the spatial stuff is only written to the saved data if you have run spatial analysis which I think is fine. I would like to stop the NAs showing up so it is just blank but that is a lower priority.

**Comment by adricaswell** [comment]
> > Spatial data is not restored if spatial analysis was not run before saving progress. Instead, all spatial data input boxes show "NA".
> 
> This one I am not going to worry about. the spatial stuff is only written to the saved data if you have run spatial analysis which I think is fine. I would like to stop the NAs showing up so it is just blank but that is a lower priority.

I agree, it is not a concern. We might just want to add it to the documentation.

**Comment by adricaswell** [comment]
The following warning pops up when navigating to the Index Results tab without allowing both Exposure Results and Spatial Vulnerability Question rasters load fully. This warning does not occur when all rasters to loaded prior to navigating to the Index Results tab.
```
Warning: Unknown or uninitialised column: `slr_vuln`.
Warning: Removed 1 row containing missing values or values outside the scale range (`geom_segment()`).
Warning: Removed 1 row containing missing values or values outside the scale range (`geom_segment()`).
```
I thought this might have something to do with being unable to generate the report when loading from previous assessment, but even when everything loads first, the report still cannot be generated.

**Comment by see24** [comment]
> The following warning pops up when navigating to the Index Results tab without allowing both Exposure Results and Spatial Vulnerability Question rasters load fully. This warning does not occur when all rasters to loaded prior to navigating to the Index Results tab.
> 
> ```
> Warning: Unknown or uninitialised column: `slr_vuln`.
> Warning: Removed 1 row containing missing values or values outside the scale range (`geom_segment()`).
> Warning: Removed 1 row containing missing values or values outside the scale range (`geom_segment()`).
> ```
> 
> I thought this might have something to do with being unable to generate the report when loading from previous assessment, but even when everything loads first, the report still cannot be generated.

Will look into this. I just pushed a commit that should fix the report generation error.

**Comment by adricaswell** [comment]
Advancing to Exposure results tab without running spatial analysis produces the following error:
```
Warning: Error in <Anonymous>: unable to find an inherited method for function ‘nlyr’ for signature ‘"NULL"’
  103: stop
  102: <Anonymous>
  101: terra::nlyr
  100: make_map [C:/Users/CaswellA/OneDrive - EC-EC/Documents/ccviR/ccviR-dev/R/app_utils_server.R#51]
   99: ::
htmlwidgets
shinyRenderWidget [C:/Users/CaswellA/OneDrive - EC-EC/Documents/ccviR/ccviR-dev/R/ccvi_app.R#1126]
   98: func
   85: renderFunc
   84: output$texp_map
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in <Anonymous>: unable to find an inherited method for function ‘nlyr’ for signature ‘"NULL"’
  103: stop
  102: <Anonymous>
  101: terra::nlyr
  100: make_map [C:/Users/CaswellA/OneDrive - EC-EC/Documents/ccviR/ccviR-dev/R/app_utils_server.R#51]
   99: ::
htmlwidgets
shinyRenderWidget [C:/Users/CaswellA/OneDrive - EC-EC/Documents/ccviR/ccviR-dev/R/ccvi_app.R#1134]
   98: func
   85: renderFunc
   84: output$cmd_map
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
```

The following error message appears in the app (for both moisture and temperature):
image

This is not an issue when running app in master branch. Only occurs in sarah-bug-fixes. This does not effect Spatial Vulnerability Questions.

**Pull request merged**
